# SPDX-License-Identifier: MIT-0
"""Debounced writer for a self-contained `.canvas.tsx`.

Mirrors cookbook/sdk/dag-task-runner/src/canvas_writer.ts.
"""

from __future__ import annotations

import json
import threading
from collections.abc import Callable
from copy import deepcopy
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Literal

from cookbook.dag_task_runner.dag import Complexity, DAG

TaskStatus = Literal["PENDING", "RUNNING", "FINISHED", "ERROR"]


@dataclass
class TaskState:
    id: str
    depends_on: list[str]
    complexity: Complexity
    subtask_prompt: str
    status: TaskStatus
    model: str
    startedAt: int | None = None
    finishedAt: int | None = None
    resultText: str | None = None
    errorMessage: str | None = None
    inputTokens: int | None = None
    outputTokens: int | None = None
    durationMs: int | None = None


@dataclass
class RunState:
    title: str
    startedAt: int
    tasks: list[TaskState]
    finishedAt: int | None = None
    runOutcome: Literal["SUCCESS", "FAILED", "INTERRUPTED"] | None = None
    runMessage: str | None = None


def initial_run_state(dag: DAG, model_for: Callable[[Complexity], str]) -> RunState:
    return RunState(
        title=dag.title,
        startedAt=__import__("time").time_ns() // 1_000_000,
        tasks=[
            TaskState(
                id=task.id,
                depends_on=list(task.depends_on),
                complexity=task.complexity,
                subtask_prompt=task.subtask_prompt,
                status="PENDING",
                model=model_for(task.complexity),
            )
            for task in dag.tasks
        ],
    )


def clone_state(state: RunState) -> RunState:
    return RunState(
        title=state.title,
        startedAt=state.startedAt,
        finishedAt=state.finishedAt,
        runOutcome=state.runOutcome,
        runMessage=state.runMessage,
        tasks=[deepcopy(task) if not isinstance(task, TaskState) else TaskState(**asdict(task)) for task in state.tasks],
    )


HEADER = """/* AUTO-GENERATED by examples/cookbook/dag_task_runner. Do not edit by hand. */
import { Card, CardBody, CardHeader, Divider, H1, H2, Pill, Row, Stack, Stat, Text } from 'cursor/canvas';

type TaskStatus = 'PENDING' | 'RUNNING' | 'FINISHED' | 'ERROR';
type Complexity = 'HIGH' | 'MED' | 'LOW';

interface TaskState {
  id: string;
  depends_on: string[];
  complexity: Complexity;
  subtask_prompt: string;
  status: TaskStatus;
  model: string;
  startedAt?: number;
  finishedAt?: number;
  resultText?: string;
  errorMessage?: string;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

interface RunState {
  title: string;
  startedAt: number;
  finishedAt?: number;
  runOutcome?: 'SUCCESS' | 'FAILED' | 'INTERRUPTED';
  runMessage?: string;
  tasks: TaskState[];
}"""

BODY = r"""function formatDuration(ms?: number): string {
  if (ms === undefined) return '—';
  if (ms < 1000) return ms + 'ms';
  const s = ms / 1000;
  if (s < 60) return s.toFixed(1) + 's';
  const m = Math.floor(s / 60);
  const rem = Math.round(s - m * 60);
  return m + 'm ' + rem + 's';
}

export default function DagRun(): JSX.Element {
  const counts = STATE.tasks.reduce(
    (acc, t) => {
      acc.total += 1;
      acc[t.status.toLowerCase() as 'pending' | 'running' | 'finished' | 'error'] += 1;
      return acc;
    },
    { total: 0, pending: 0, running: 0, finished: 0, error: 0 },
  );
  const statusLabel =
    STATE.runOutcome === 'INTERRUPTED'
      ? 'INTERRUPTED'
      : STATE.runOutcome === 'FAILED'
        ? 'FAILED'
        : STATE.finishedAt !== undefined
          ? 'COMPLETE'
          : 'RUNNING';
  return (
    <Stack gap={16}>
      <Stack gap={6}>
        <H1>{STATE.title}</H1>
        <Row gap={10} align="center">
          <Pill tone="info" active size="sm">{statusLabel}</Pill>
          <Text tone="secondary" size="small">{counts.total} tasks</Text>
        </Row>
        {STATE.runMessage ? <Text tone="secondary" size="small">{STATE.runMessage}</Text> : null}
      </Stack>
      <Stack gap={12}>
        <H2>Tasks</H2>
        {STATE.tasks.map((t) => (
          <Card key={t.id}>
            <CardHeader trailing={<Pill size="sm">{t.status}</Pill>}>{t.id}</CardHeader>
            <CardBody>
              <Stack gap={6}>
                <Text size="small" tone="secondary">Model {t.model}</Text>
                <Text size="small">{t.subtask_prompt}</Text>
                {t.resultText ? <Text size="small">{t.resultText}</Text> : null}
                {t.errorMessage ? <Text size="small">Error: {t.errorMessage}</Text> : null}
              </Stack>
            </CardBody>
          </Card>
        ))}
      </Stack>
    </Stack>
  );
}
"""


def render_canvas_source(state: RunState) -> str:
    payload = asdict(state)
    state_literal = json.dumps(payload, indent=2)
    return f"{HEADER}\n\nconst STATE: RunState = {state_literal};\n\n{BODY}\n"


class CanvasWriter:
    def __init__(self, canvas_path: str, debounce_ms: int = 200) -> None:
        self.canvas_path = canvas_path
        self.debounce_ms = debounce_ms
        self._pending: RunState | None = None
        self._timer: threading.Timer | None = None
        self._lock = threading.Lock()
        self._last_error: BaseException | None = None

    def schedule(self, state: RunState) -> None:
        with self._lock:
            self._pending = clone_state(state)
            if self._timer is not None:
                return
            self._timer = threading.Timer(self.debounce_ms / 1000, self._flush_timer)
            self._timer.daemon = True
            self._timer.start()

    def _flush_timer(self) -> None:
        with self._lock:
            self._timer = None
            snapshot = self._pending
            self._pending = None
        if snapshot is not None:
            self._write_now(snapshot)

    def flush(self) -> None:
        with self._lock:
            if self._timer is not None:
                self._timer.cancel()
                self._timer = None
            snapshot = self._pending
            self._pending = None
        if snapshot is not None:
            self._write_now(snapshot)
        if self._last_error is not None:
            raise self._last_error

    def _write_now(self, state: RunState) -> None:
        try:
            path = Path(self.canvas_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render_canvas_source(state), encoding="utf-8")
            self._last_error = None
        except BaseException as exc:
            self._last_error = exc
            raise
